#pragma once

enum node_type
{
	SPHERE = 1, PLANE, PLUS, MINUS, MULTIPLE, CONE, CYLINDER, TORUS, POLYGON, CUBE, TEAPOT,
	NURBS_SPHERE, NURBS_CUBE, NURBS_CYLINDER, NURBS_CONE, NURBS_PLANE, NURBS_TORUS, NURBS_CIRCLE, NURBS_SQUARE,
};
